version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: "no"
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: COMPAN|0N
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
